name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [dev]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      # 运行构建脚本
      - name: Build VuePress site
        run: yarn docs:build

      # @see https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository
      # issue: https://github.com/peaceiris/actions-gh-pages/issues/682
      # issue: https://github.com/peaceiris/actions-gh-pages/issues/339
      #
      # When you use deploy_key, set your private key to the repository which includes this action and set your public key to your external repository.
      #
      # run : ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f <private_repo_name> -N ""
      #
      # 1. Set private key in private repository: Settings > Secrets(Actions) > New repository secret
      #
      # 2. Set public  key in public  repository: Settings > Deploy keys > Add deploy key (enable "Allow write access"")
      - name: Deploy to External GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: HenryZhuHR/mobile_robot-ros2.docs
          publish_branch: main  # default: gh-pages
          publish_dir: docs/.vuepress/dist

