name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [actions]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout this
        # https://github.com/actions/checkout
        # 拉取私有子模块参考: https://github.com/actions/checkout/issues/924#issuecomment-1563701878
        uses: actions/checkout@v3
        # with:
        #   ssh-key: ${{ secrets.SSH_KEY }}
        #   submodules: true

      # - name: Checkout core
      #   # https://github.com/actions/checkout
      #   # https://zhuanlan.zhihu.com/p/408319831
      #   # Makesure PAT has repo scope
      #   uses: actions/checkout@v3
      #   with:
      #     repository: HenryZhuHR/mobile_robot-core
      #     path: core
      #     token: ${{ secrets.MOBILE_ROBOT_CORE_SECRET }} # `GH_PAT` is a secret that contains your PAT
      #     fetch-depth: 1
          
      - name: Contribute List 
        # https://github.com/marketplace/actions/contribute-list
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use_username: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      # 运行构建脚本
      - name: Build VuePress site
        run: yarn docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 docs 分支
          target_branch: docs
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

